context:
  name: texgen
  version: "3.13.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # url: https://github.com/louisepb/TexGen/archive/refs/tags/v${{ version }}.tar.gz
  # sha256: 4E49837ACEBAC59DD03E269E3D23D034569E4E436C8D6395F3B568AA08C4F6A1
  # does not work?! Cloning into '/d/XXX/Code/staged-recipes/build_artifacts/src_cache/TexGen.git'...
  # fatal: unable to access 'https://github.com/louisepb/TexGen.git/': error setting certificate file: /usr/ssl/certs/ca-bundle.crt
  # git: https://github.com/louisepb/TexGen.git
  # branch: main
  path: ../../../TexGen
  patches:
    - fix-windows-linking.patch

build:
  script:
    content: |
        cmake ^
          -G "Visual Studio 17 2022" ^
          -A x64 ^
          -DBUILD_CASCADE_EXPORT=OFF ^
          -DBUILD_DOCUMENTATION=OFF ^
          -DBUILD_EXAMPLES=OFF ^
          -DBUILD_GUI=OFF ^
          -DBUILD_PYTHON_INTERFACE=OFF ^
          -DBUILD_RENDERER=OFF ^
          -DBUILD_SHARED=ON ^
          -DBUILD_UNIT_TESTS=OFF ^
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ^
          -DCMAKE_CXX_STANDARD=14 ^
          "%SRC_DIR%"
        cmake --build . --config Release

    env:
      BUILD_CASCADE_EXPORT: "OFF"
      BUILD_DOCUMENTATION: "OFF"
      BUILD_EXAMPLES: "OFF"
      BUILD_GUI: "OFF"
      BUILD_PYTHON_INTERFACE: "OFF"
      BUILD_RENDERER: "OFF"
      BUILD_SHARED: "ON"
      BUILD_UNIT_TESTS: "OFF"
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake

about:
  homepage: https://texgen.sourceforge.io/index.php/Main_Page
  summary: 'TexGen is a geometric textile modelling software package to be used for obtaining engineering properties of woven textiles and textile composites.'
  description: |
    TexGen is a geometric textile modelling software package to be used for obtaining engineering properties of woven textiles and textile composites.
  license: GPL-2.0
  license_file: LICENSE
  repository: https://github.com/louisepb/TexGen

extra:
  recipe-maintainers:
    - claudiushaag
