{% set name = "pocker" %}
{% set version = "1.17.5" %}
{% set python_min = "3.10.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pocker_tui/pocker_tui-{{ version }}.tar.gz
  sha256: e020b1fb382bc78d3682c73717735ca7a4785349454b376ddd55649ca8571568

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - pocker = application.main:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >= {{ python_min }}
    - docker-py >= 7.0.0,<8.0
    - textual >= 0.79.0
    - pyyaml >= 6.0.1
    - pydantic >= 2.7.3
    - click >= 8.1.7
    - colorama >= 0.4.6
    - yaspin >= 3.0.2
    - packaging >= 24.1
    - textual-plotext >= 0.2.1
    - pyte >= 0.8.1
    - __unix  # [unix]
    - __win  # [win]
    - pywinpty >= 2.0.13  # [win]


test:
  commands:
    - pocker --help
  requires:
    - python {{ python_min }}

about:
  homepage: https://github.com/pommee/Pocker
  summary: '~ TUI tool for docker ~'
  description: |
    Pocker is a TUI tool to help with docker related tasks. For example,
      - View containers/images.
      - Manage status of containers.
      - See logs, attributes, environment variables and container statistics.
      - Filter logs based on keywords.
      - Start shell inside a container.
      - Customize configuration, i.e keybinds and behaviour.
    The tool is heavily based on docker-py and textual.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag