context:
  name: pocker
  pypi_name: pocker-tui
  version: "1.17.2"
  python_min: "3.10.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ pypi_name | replace("-", "_") }}/${{ pypi_name | replace("-", "_") }}-${{ version }}.tar.gz
  sha256: aeeb5223cd39391ee445a7051446628aa0d4a5c978fd4697a8705cf320351807

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0
  python:
    entry_points:
      - pocker = application.main:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core
  run:
    - python >=${{ python_min }}
    - docker-py >= 7.0.0,<8.0
    - textual >= 0.88.0,<1.0
    - pyyaml >= 6.0.1,<7.0
    - pydantic >= 2.7.3,<3.0
    - click >= 8.1.7,<9.0
    - colorama >= 0.4.6,<0.5
    - yaspin >= 2.2,<4.0
    - packaging >= 24.1,<25.0
    # - pywinpty >= { version = "^2.0.13", platform = "win32" }
    - textual-plotext >= 0.2.1,<0.3

tests:
  - script:
    - pocker
    requirements:
      run:
        - python ${{ python_min }}.*


about:
  homepage: https://github.com/pommee/Pocker
  summary: '~ TUI tool for docker ~'
  description: |
    Pocker is a TUI tool to help with docker related tasks. For example,
      - View containers/images.
      - Manage status of containers.
      - See logs, attributes, environment variables and container statistics.
      - Filter logs based on keywords.
      - Start shell inside a container.
      - Customize configuration, i.e keybinds and behaviour.
    The tool is heavily based on docker-py and textual.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
    - pommee
