context:
  name: netron
  version: "8.2.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/lutzroeder/netron/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1c1881adc5e47765ff51fcedd82dc6100ad419a2df514b965a53a28b2fd395bf

build:
  noarch: python
  script:
    - python package.py build
    - python -m build -n -s --outdir dist/pypi dist/pypi
    - python -m pip install -vv dist/pypi/*.tar.gz
  number: 0
  python:
      entry_points:
        - netron = netron:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=42
    - python-build
    - wheel
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
      - netron
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - netron --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/lutzroeder/netron
  summary: 'Netron is a viewer for neural network, deep learning and machine learning models.'
  description: |
    Netron supports ONNX, TensorFlow Lite, Core ML, Keras, Caffe, Darknet, PyTorch, TensorFlow.js, Safetensors and NumPy.
    Netron has experimental support for TorchScript, TensorFlow, MXNet, OpenVINO, RKNN, ML.NET, ncnn, MNN, PaddlePaddle, GGUF and scikit-learn.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
